version: '3'

services:
  localsite-ai:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      # Choose the default provider (deepseek, openai_compatible, ollama, or lm_studio)
      - DEFAULT_PROVIDER=lm_studio
      
      # DeepSeek Configuration (uncomment and add your API key to use DeepSeek)
      # - DEEPSEEK_API_KEY=your_deepseek_api_key_here
      # - DEEPSEEK_API_BASE=https://api.deepseek.com/v1
      
      # OpenAI Compatible Configuration (uncomment and add your API key to use custom OpenAI-compatible API)
      # - OPENAI_COMPATIBLE_API_KEY=your_openai_compatible_api_key_here
      # - OPENAI_COMPATIBLE_API_BASE=https://api.openai.com/v1
    # volumes:
    #   - ./:/app
    extra_hosts:
      # Important: Allows access to the host machine
      - "host.docker.internal:host-gateway"